/**
 * File: form-dynamic.js
 * Created: 2025-12-18 18:56:34
 * Last Modified: 2025-12-24 12:45:00
 * 
 * Dynamic Form Handlers
 * 
 * Provides client-side enhancements for dynamically generated forms.
 * Works in conjunction with the dynamic-form.ejs partial to add interactive
 * features that improve user experience.
 * 
 * KEY FEATURES:
 * 1. Character Counters: Real-time character counting for textareas with maxlength
 * 2. Tooltip Initialization: Activates Bootstrap tooltips on form elements
 * 3. Form Validation: HTML5 validation API integration
 * 4. Data Extraction: Converts form data to JavaScript objects
 * 
 * AUTO-INITIALIZATION:
 * Forms with class="dynamic-form" and data-auto-init="true" are automatically
 * initialized on page load. Otherwise, call initializeDynamicForm(formId) manually.
 * 
 * USAGE:
 * import { initializeDynamicForm, getFormData, resetForm } from './form-dynamic.js';
 * initializeDynamicForm('myFormId');
 */

'use strict';

/**
 * Initialize a dynamic form with client-side enhancements
 * 
 * Sets up interactive features for forms generated by the dynamic-form.ejs partial.
 * This function should be called once per form, typically on page load or after
 * dynamically inserting a form into the DOM.
 * 
 * WHAT IT DOES:
 * 1. Activates character counters for textareas with maxlength attribute
 * 2. Initializes Bootstrap tooltips for help text and validation messages
 * 3. Logs debug information if config.debug !== false
 * 
 * The config parameter is optional and mainly used for debugging. Most forms
 * don't need to pass any configuration.
 * 
 * @param {string} formId - The form element ID (must exist in DOM)
 * @param {object} config - Optional configuration object with debug flag and metadata
 * @param {boolean} config.debug - Enable console logging (default: true)
 * 
 * @example
 * // Simple initialization
 * initializeDynamicForm('appForm');
 * 
 * // With debug disabled
 * initializeDynamicForm('appForm', { debug: false });
 */
export function initializeDynamicForm(formId, config = {}) {
  const form = document.getElementById(formId);
  if (!form) {
    console.error('Dynamic Form: Form not found:', formId);
    return;
  }

  // Initialize character counters for textareas with maxlength
  initializeCharacterCounters(formId);

  // Initialize Bootstrap tooltips
  initializeTooltips(formId);

  // Debug info
  if (config.debug !== false) {
    console.log('Dynamic Form Initialized:', {
      formId: formId,
      appDataSourceLength: config.appDataSourceLength || 0,
      fieldCount: config.fieldCount || 0,
      fields: config.fields || []
    });
  }
}

/**
 * Initialize character counters for textareas with maxlength attribute
 * 
 * Finds all textareas within the form that have a maxlength attribute and
 * updates the corresponding counter display (.char-count) as the user types.
 * The counter shows the current character count (not remaining characters).
 * 
 * EXPECTED HTML STRUCTURE:
 * <div class="mb-3">
 *   <textarea maxlength="500" ...></textarea>
 *   <small class="char-count">0</small> / 500 characters
 * </div>
 * 
 * The counter element must:
 * - Have class="char-count"
 * - Be a child of the same parent element as the textarea
 * 
 * @param {string} formId - The form element ID containing the textareas
 * @private
 */
const initializeCharacterCounters = (formId) => {
  const textareas = document.querySelectorAll(`#${formId} textarea[maxlength]`);
  
  textareas.forEach(textarea => {
    const updateCounter = () => {
      const counter = textarea.parentElement.querySelector('.char-count');
      if (counter) {
        counter.textContent = textarea.value.length;
      }
    };
    
    textarea.addEventListener('input', updateCounter);
    updateCounter(); // Initialize counter on load
  });
}

/**
 * Initialize Bootstrap tooltips for form elements
 * @param {string} formId - The form element ID
 */
const initializeTooltips = (formId) => {
  const tooltipTriggerList = document.querySelectorAll(`#${formId} [data-bs-toggle="tooltip"]`);
  [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
}

/**
 * Validate form before submission
 * @param {HTMLFormElement} form - The form element
 * @returns {boolean} - True if valid, false otherwise
 */
export function validateForm(form) {
  if (!form.checkValidity()) {
    form.classList.add('was-validated');
    return false;
  }
  return true;
}

/**
 * Get form data as an object
 * @param {string} formId - The form element ID
 * @returns {object} - Form data as key-value pairs
 */
export function getFormData(formId) {
  const form = document.getElementById(formId);
  if (!form) return {};
  
  const formData = new FormData(form);
  const data = {};
  
  for (const [key, value] of formData.entries()) {
    data[key] = value;
  }
  
  return data;
}

/**
 * Reset form and remove validation states
 * 
 * Performs a complete form reset including:
 * 1. Clears all input values (calls native form.reset())
 * 2. Removes Bootstrap validation styling (was-validated class)
 * 3. Resets character counters to 0
 * 
 * This is useful when:
 * - Canceling an edit operation
 * - Switching from Edit mode to Add mode
 * - After successful form submission
 * - Closing a modal with unsaved changes
 * 
 * @param {string} formId - The form element ID to reset
 * 
 * @example
 * // Reset form when modal is closed
 * $('#myModal').on('hidden.bs.modal', () => {
 *   resetForm('appForm');
 * });
 */
export function resetForm(formId) {
  const form = document.getElementById(formId);
  if (!form) return;
  
  form.reset();
  form.classList.remove('was-validated');
  
  // Reset character counters
  const counters = form.querySelectorAll('.char-count');
  counters.forEach(counter => {
    counter.textContent = '0';
  });
}

// Auto-initialize forms with data-auto-init attribute
document.addEventListener('DOMContentLoaded', () => {
  const autoInitForms = document.querySelectorAll('.dynamic-form[data-auto-init="true"]');
  
  autoInitForms.forEach(form => {
    const configAttr = form.getAttribute('data-form-config');
    const config = configAttr ? JSON.parse(configAttr) : {};
    initializeDynamicForm(form.id, config);
  });
});
